### ISSUE TITLE
Question: How can existing project benefit by using it?

### ISSUE THREAD

**Issue by stefanos82** [hollodotme/fast-cgi-client#10]
First of all, kudos for doing this amazing work. 

Your project reminds me of swoole.

My question is rather naive. For instance, let's say that I have a WordPress website. 

How can I benefit from switching it to fastcgi-client and feasible is to do so?

**Comment by hollodotme** [comment]
Hi @stefanos82,

First: Thanks!

I don't know if I get your question right, but after I shortly looked into swoole, I think there is a big difference between fast-cgi-client and swoole regarding the target problem space. 

fast-cgi-client itself is not meant to replace a webserver like nginx or apache. In combination with loop implementations like e.g. [ReactPHP](https://github.com/reactphp) or swoole it could be achievable though. 

But the problem space I am targeting with fast-cgi-client is background workers and parallelisation without any extra extensions like pcntl, pthreads or gearman using build-in php-fpm as the process manager / queue.

A basic example is:
1. You call a `main.php` script via Webserver or CLI
2. This `main.php` script sends multiple requests via fast-cgi-client to php-fpm to process things in parallel in background (without a webserver involved)
3. The `main.php` waits until all background processes have finished and responds. 

The "waits until all background processes have finished" is optional. 
You may also just do fire-and-forget requests to php-fpm, so `main.php` responds immediately.

But like always it heavily depends on your specific use-case or problem you want to solve.

You can have a look at my 2 experimental blog post where fast-cgi-client is used:
* https://hollo.me/php/experimental-async-php-volume-1.html
* https://hollo.me/php/experimental-async-php-volume-2.html

Please reach out again, if I misunderstood your question. It would be helpful, if you could describe your problem in more detail.

Thanks, Holger

**Comment by stefanos82** [comment]
Hey @hollodotme, thank you for your reply.

About swoole I meant the way both work from an asynchronous point of view.

Now about the last part of my question.

I didn't say it should replace NGINX; actually I use NGINX that works with fastcgi-fpm.

What I wanted to know is whether is plausible to replace the standard fastcgi-fpm with your fastcgi-client and whether it's possible to use it with any WordPress website.

I want to see how beneficial it can be, just out of pure curiosity.

**Comment by hollodotme** [comment]
Hey @stefanos82, ok now I understand. 

But again, this library is not meant to replace fastcgi-fpm / php-fpm. It is a _client_ that allows you to directly communicate with fastcgi-fpm / php-fpm right out of your PHP code - without the roundtrip over nginx or the like.

So to use this lib you'll need a running php-fpm server. 

Typically you have a "www" pool that is used by your nginx to handle web requests. I recommend adding a separate pool e.g. "worker" pool on a different socket/port for handling background workers / requests from fast-cgi-client.

You can find such pool configs here: 
* https://github.com/hollodotme/fast-cgi-client/blob/v2.3.0/env/php-fpm/7.0/network-socket.pool.conf
* https://github.com/hollodotme/fast-cgi-client/blob/v2.3.0/env/php-fpm/7.0/unix-domain-socket.pool.conf

You maybe wanna have a look into my talk slides about this project to get a broader idea of what the project is about. https://speakerdeck.com/hollodotme/async-php-requests-and-reactive-responses-with-php-fpm

You can use the lib in any PHP project as long as it is PHP 7.x compatible. So integration in a WordPress website is definitely possible, if you have a suitable use-case.

I hope that helps.

Cheers, Holger

**Comment by stefanos82** [comment]
I have read your presentation, that's why I starred your project, so I can study it more afterwards.

By the way, you mention quite a lot about "nirwana" in your slides. 

Is it a service, a mechanism, or did you mean "nirvana" and it's an innocent typo?

Another question related to your article [Experimental async PHP - Volume 2](https://hollo.me/php/experimental-async-php-volume-2.html): the first video has a humongous resolution and when run via browser's default HTML5 video player, it consumes 100% CPU of 4 cores under Chromium (Debian testing 64-bit) and nearly 80% CPU of 4 cores with Firefox.

I have re-encoded the video with handbrake at a lower resolution, a 720p30 to be honest with you and it dropped to nearly 2% CPU usage.

The second video plays normal comparing the first one.

Now about your suggestions, I will do my best to fully comprehend it by playing around it until it finally clicks lol.

Right now it's not that clear, but I have got a rough idea around it.

Cheers.

**Comment by hollodotme** [comment]
About "nirwana": Damn, yes it is a typo. I meant "nirvana". In German it is written with a "w". -.-

About the video: Thanks for pointing out. Since you already re-encoded it, could you provide a PR to https://github.com/hollodotme/hollo.me/tree/master/public/video/php and replace it? That would be awesome!

I started writing a new blog post about a real-world example from my company using the fast-cgi-client. I think I can finish it at the weekend. Maybe this is more helpful.

For now I'd close this issue. Please feel free to open a new one if you have specific questions or problems regarding the lib.
