### ISSUE TITLE
php 7.0.23 problem

### ISSUE THREAD

**Issue by parsibox** [hollodotme/fast-cgi-client#25]
hi
not work with php 7.0.23
```
Fatal error: Uncaught Error: Class 'hollodotme\FastCGI\Requests\PostRequest' not found
```
i install with this
```
composer require hollodotme/fast-cgi-client:^1.0
```
this is my code
```
<?php
// /var/www/index.php
require __DIR__ . '/vendor/autoload.php';
use hollodotme\FastCGI\Client;
use hollodotme\FastCGI\SocketConnections\UnixDomainSocket;
use hollodotme\FastCGI\Requests\PostRequest;

$connection = new UnixDomainSocket('/var/run/php/php7.0-fpm.sock', 5000, 5000);
$client = new Client($connection);
$content = http_build_query(['task' => 'SendMail', 'payload' => json_encode('...')]);

$request = new PostRequest('/var/www/worker.php', $content);
$client->sendAsyncRequest($request);
```

**Comment by hollodotme** [comment]
Hi @parsibox,

thanks for the issue. 
Unfortunately I am not able to reproduce it. Please have a look at my test setup which proves that your code above is working.

👉https://github.com/hollodotme/github-issues/tree/master/fast-cgi-client/25

And a gentle reminder: The v1.x / PHP 7.0 versions of this library are no longer maintained. Please consider upgrading to v2.x / PHP >= 7.1. 😄

**Comment by parsibox** [comment]
it is so hard to change php version in my server
i have other error in php 7.0.23
when i use async only first request run  but i get requestid for all request
Request sent, got ID: 44153Request sent, got ID: 29650

**Comment by hollodotme** [comment]
Hi @parsibox, sorry, but I don't understand what you mean with 
>only first request run but i get requestid for all request
>Request sent, got ID: 44153Request sent, got ID: 29650

My questions:
* How do you collect the responses? (Do you collect them at all?)
* How many requests do you send?
* How do you see that only the first request runs?
* How can I reproduce it? Can you provide example code again?

**Comment by parsibox** [comment]
i send 2 request
```
$requestId1 = $client->sendAsyncRequest($request1);
$requestId2 = $client->sendAsyncRequest($request1);
```
then print the requestid
```
echo "Request sent, got ID: {$requestId1}";
echo "Request sent, got ID: {$requestId2}";
```
thene i get this 
```
 Request sent, got ID: 44153Request sent, got ID: 29650
```
but only first request run ( only $requestId1 actually run  )

**Comment by hollodotme** [comment]
Again, how do you see that only the first request runs?

**Comment by parsibox** [comment]
i write a log file in my php worker.( send an email when php worker run  & i receive only 1 email )

**Comment by hollodotme** [comment]
I updated the code at https://github.com/hollodotme/github-issues/tree/master/fast-cgi-client/25, so the request will be sent 2 times and a log file is written by the `worker.php`.

As you can see, I have 2 lines in the log file, one for each request.

A wild guess of mine is, that your email server is "clever enough" not to send the same email within 1 second. Try to replace sending emails with a real log file and you should see that the worker is called 2 times.

**Comment by parsibox** [comment]
when i use PostRequest in php 7.0.23 it say 
```
Fatal error: Uncaught Error: Class 'hollodotme\FastCGI\Requests\PostRequest' not found
```
i install version 1.x 

are you sure you test this version?

**Comment by parsibox** [comment]
i tested this code again and record a movie
please download the movie from https://ufile.io/xjkv5
```

<?php
// /var/www/index.php
require __DIR__ . '/vendor/autoload.php';
use hollodotme\FastCGI\Client;
use hollodotme\FastCGI\Requests\PostRequest;
use hollodotme\FastCGI\SocketConnections\UnixDomainSocket;

$connection = new UnixDomainSocket('unix:///usr/local/php70/sockets/webapps.sock', 5000, 5000);
$client = new Client($connection);

$environment = [
    'REQUEST_METHOD'  => 'GET',
    'SCRIPT_FILENAME' => '/var/www/html/1.php',
];
$requestId=$client->sendAsyncRequest( $environment, '' );
echo "Request sent, got ID: {$requestId}";
$environment = [
    'REQUEST_METHOD'  => 'GET',
    'SCRIPT_FILENAME' => '/var/www/html/2.php',
];
$requestId=$client->sendAsyncRequest( $environment, '' );
echo "Request sent, got ID: {$requestId}";

echo "Responses:\n\n";
while ( $client->hasUnhandledResponses() )
{
	foreach ( $client->readReadyResponses() as $response )
	{
		echo $response->getBody(), "\n";
	}
}
```

**Comment by hollodotme** [comment]
If you install v1.x with the composer command that you stated in your first comment

> composer require hollodotme/fast-cgi-client:^1.0

it should install v1.4.2 of the library.

With this version your code above cannot work, as `$client->sendAsyncRequest()` requires an object that implements `ProvidesRequestData`, not an array.

Can you please check what version of the library you have installed exactly?
(What does `composer info` say?)

PS: Your video doesn't play on my machine.

**Comment by parsibox** [comment]
```
{
    "require": {
        "hollodotme/fast-cgi-client": "1.0"
    }
}

```
i will try to update it to 1.4.2

**Comment by parsibox** [comment]
i installed 1.4.2 and my problem solved
thanks a lot
