### ISSUE TITLE
Allow multi value headers

### ISSUE THREAD

**Issue by hollodotme** [hollodotme/fast-cgi-client#35]
## Expected Behavior

1. A call to `Response#getHeaders()` will return a two-dimensional array like this:

```php
$expectedHeaders = [
    'Set-Cookie' => [
        'yummy_cookie=choco',
        'tasty_cookie=strawberry',
    ],
    'Status' => [
        'HTTP/2.0 200 OK'
    ],
    'Content-type' => [
        'text/html; charset=utf-8',
    ],
];

$this->assertSame($expectedHeaders, $response->getHeaders());
```

2. A call to `Response#getHeader($headerKey)` will return a flat array with all values for the given key.

```php
$expectedHeaderValues = [
    'yummy_cookie=choco',
    'tasty_cookie=strawberry',
];

$this->assertSame($expectedHeaderValues, $response->getHeader('Set-Cookie'));
```

3. A call to a new method `Response#getHeaderLine($headerKey)` will return all values, separated by comma, for the given key.

4. The results of `Response#getHeader($headerKey)` and `Response#getHeaderLine($headerKey)` will be the same for given keys in different case. (case-insensitive keys are accepted)

## Actual Behavior

1. Currently a call to `Response#getHeaders()` will return a flat key-value array and provide only the last value of a multi-value header.

```php
[
    'Set-Cookie' => 'tasty_cookie=strawberry',
    'Status' => 'HTTP/2.0 200 OK',
    'Content-type' => 'text/html; charset=utf-8',
];
```

2. Currently a call to `Response#getHeader($headerKey)` will return a string containing the last value for the given key.

3. A method `Response#getHeaderLine($headerKey)` does not exist.

4. Header keys are currently case-sensitive in `Response#getHeader($headerKey)`.

## Steps to Reproduce the Problem

1. Create a worker script that sends the following headers:
   ```php
   header('Status: HTTP/2.0 200 OK');
   header('Set-Cookie: yummy_cookie=choco');
   header('Set-Cookie: tasty_cookie=strawberry');
   header('Content-type: text/html; charset=utf-8');
   ```
2. Issue a GET request to the worker script via the FastCGI client.
3. Read the headers using `Response#getHeaders()` or `Response#getHeader('Set-Cookie')` respectively.

## Specifications

- Package version: `<=2.7.0`
- PHP version: `ALL`
- Platform/OS: `ALL`

## Further comments

Changing the return type of `Response#getHeaders()` and `Response#getHeader($headerKey)` to `array` is a BC break and requires a new major version.

Proposed version: `3.0.0`

**Comment by mnapoli** [comment]
:+1: 

Do you think it could make sense to add a new method like `getMultiHeader($key)` to keep BC? Maybe it's not as clean as you want it to be though, in any case both options are fine for Bref since it's still wip ^^

**Comment by hollodotme** [comment]
@mnapoli I think I'll go with the [PSR standard](https://www.php-fig.org/psr/psr-7/#headers-with-multiple-values) and also implement `Response#getHeaderLine($headerKey)` that returns a string with all header values.

So in the end:
```php
public function getHeaders() : array # two-dimensional as state above

public function getHeader(string $headerKey) : array # 1-dimensional containing all values of the header

public function getHeaderLine(string $headerKey) : string # all values separated with comma
```

**Comment by mnapoli** [comment]
:+1: makes sense!
