### ISSUE TITLE
3.0 Release?

### ISSUE THREAD

**Issue by gabel** [hollodotme/fast-cgi-client#49]
Any plans to release 3.0 stable soon?

**Comment by hollodotme** [comment]
Released [v3.0.0](https://github.com/hollodotme/fast-cgi-client/tree/v3.0.0) - [CHANGELOG](https://github.com/hollodotme/fast-cgi-client/blob/v3.0.0/CHANGELOG.md)

**Comment by gabel** [comment]
Thanks. Makes life easier on composer prefer-stable setting...
