### ISSUE TITLE
How do I add a header parameter to a request 

### ISSUE THREAD

**Issue by guodong-xia** [hollodotme/fast-cgi-client#50]

**Comment by hollodotme** [comment]
Hi @guodong-xia,

Usually HTTP headers are represented as a key-values in the `$_SERVER` array, prefixed with `HTTP_`, like:
```php
$_SERVER['HTTP_ACCEPT'] = 'text/html';
```

These key-values are usually created by the webserver instance (nginx or apache). As there is no webserver involved for the request via fastCGIClient, the only way you can set those key-values is:

```php
$request = new PostRequest('/path/to/script.php', 'content');
$request->setCustomVar('HTTP_ACCEPT', 'text/html');
```

Same goes for any other value that you wanna have in the `$_SERVER` array on the script side.

If this is not what you asked for, please elaborate on what you're trying to do.

Thank you.

**Comment by hollodotme** [comment]
@guodong-xia Did this answer your question?

**Comment by guodong-xia** [comment]
That's a great answer, solved my problem, Thank you very much.
