### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by themsaid** [hollodotme/fast-cgi-client#51]
## Specifications

- Package version: 3.0
- PHP version: 7.4
- Platform/OS: Ubuntu 18.04

Running this under PHP 7.4 results the following error:

Uncaught ErrorException: Array and string offset access syntax with curly braces is deprecated in /tmp/vendor/hollodotme/fast-cgi-client/src/Sockets/Socket.php:435

**Comment by hollodotme** [comment]
Thank you @themsaid!

I merged your changes from #52 and additionally:

- added PHP 7.4 to CI pipelines
- enabled deprecation warnings in PHPUnit 🤦‍♂
