### ISSUE TITLE
BC-Break with final constructor in AbstractRequest

### ISSUE THREAD

**Issue by hollodotme** [hollodotme/fast-cgi-client#56]
## Expected Behavior

The constructor signature of a derived class from `AbstractRequest` shall be changeble.

## Actual Behavior

Derived classes of `AbstractRequest` cannot overwrite the constructor signature as it is declared final.

## Steps to Reproduce the Problem

1. Create a derived class from AbstractRequest
2. Add a constructor with a different signature

## Specifications

- Package version: 3.1.0
- PHP version: 7.1-7.4

## Further comments

* See: https://github.com/hollodotme/fast-cgi-client/pull/55
* See: https://github.com/hollodotme/fast-cgi-client/commit/035c24c7e9434307a6f8a14ebbfda9bbd8f328c6#r38980332

**Comment by hollodotme** [comment]
## Solution

* Remove the named constructor `::newWithRequestContent()` from `AbstractRequest`
* Remove the named constructor `::newWithRequestContent()` from interface `ProvidesRequestData` in order avoid required implementation in userland derived classes from `AbstractRequest`.
* Add named constructor `::newWithRequestContent()` to all derived request classes separately in order to avoid `new static()` calls.

CC: @Nyholm, @mnapoli

**Comment by taylorotwell** [comment]
This has bitten us on Laravel Vapor.

**Comment by Nyholm** [comment]
Thank you for fixing this quickly. 

This will be okey if one updates from 3.0.1 to 3.1.1. However, since you removed a function you introduced another BC break for 3.1.0 to 3.1.1. 

https://github.com/hollodotme/fast-cgi-client/compare/v3.1.0...v3.1.1

Im not sure what the best way forward now is.

**Comment by mnapoli** [comment]
Thank you for the quick fix!

The "BC break" between 3.1.0 and 3.1.1 would sound acceptable to me since this is a fix (and the release was live only for a few hours so it's unlikely someone built something on it, but that's just my opinion ^^

**Comment by Nyholm** [comment]
Yeah, sure. That is true. 

So Im okey with marking 3.1.0 as "buggy version" and continue development on 3.1.1 as normal.
