### ISSUE TITLE
Response never returned

### ISSUE THREAD

**Issue by gordalina** [hollodotme/fast-cgi-client#60]
## Expected Behavior

Response to return

## Actual Behavior

Stuck in `fetchResponse()`

## Steps to Reproduce the Problem

Can't reproduce reliablty

## Specifications

- Package version: unknown
- PHP version: unknown
- Platform/OS: unknown
- Subsystem: unknown

## Further comments

Issue initially reported here: https://github.com/gordalina/cachetool/issues/147
@Vanav can provide more details.

**Comment by hollodotme** [comment]
@gordalina / @Vanav Thanks for the issue. I need more details in order to reproduce or identify the problem. 

1. What is the used version of the library?
2. What is the used PHP version? (client-side and server-side, if they differ)
3. Some words about the use-case and the failing scenario.
4. Code of the fast-cgi-client request 
5. The script that is being called through the fast-cgi-request on server side.

**Comment by hollodotme** [comment]
Hi @gordalina & @Vanav, do you have any input to reproduce the issue?

**Comment by gordalina** [comment]
@hollodotme, I have never encountered this issue and from the reports I've received, it is not an issue that can be reproduced consistently.

**Comment by Vanav** [comment]
If happens from time to time on different servers and environments. Right now I have one halted script.
1. CacheTool 4.1.1
2. PHP 7.4.7, Ubuntu 18.04.4, php-fpm unix socket.
3. Need to make a call to php-fpm to reset opcache.
4, 5. `cachetool -vvv opcache:reset`
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
deployer  5394  0.0  0.1 369596 35104 ?        S    12:29   0:00 php /usr/bin/cachetool opcache:reset
```

**Comment by hollodotme** [comment]
@Vanav Thanks. 

Can you please provide the code that executes the request to php-fpm and fetches the response. (I guess this is the code in the `opcache:reset` command.)

And can you please provide the code of the script that is called on the server(s) via php-fpm in that case.

**Comment by hollodotme** [comment]
@Vanav Do you also see what is happening on the server that is called through php-fpm? A hanging `fetchResponse()` simply indicates that the called server is not responding or takes longer than expected to execute the request.

Also, are you executing the same request on multiple servers with that command? 

And what version of the fast-cgi-client is used in CacheTool 4.1.1?

**Comment by Vanav** [comment]
Created file `/dev/shm/cachetool-5f1e9e8452faa.php` with contents:
```
<?php
if (extension_loaded('newrelic')) {
    newrelic_ignore_transaction();
}

$errors = array();

$cachetool_error_handler_5f1e9e8452fc8 = function($errno, $errstr, $errfile, $errline) use (&$errors) {
    $errors[] = array(
        'no' => $errno,
        'str' => $errstr,
    );
};

$cachetool_exec_5f1e9e8452fc8 = function() use (&$errors) {
    try {
        return extension_loaded('Zend OPcache');
    } catch (\Exception $e) {
        $errors[] = array(
            'no' => $e->getCode(),
            'str' => $e->getMessage(),
        );
    }
};

set_error_handler($cachetool_error_handler_5f1e9e8452fc8);

$result = $cachetool_exec_5f1e9e8452fc8();

echo serialize(array(
    'result' => $result,
    'errors' => $errors
));
```
This file is executed via php-fpm unix socket. php-fpm access log:
```
27/Jul/2020:12:29:40 +0300 "POST " status:200 req_time:0.313 mem:2048 cpu:0.00% script:/dev/shm/cachetool-5f1e9e8452faa.php
```
This looks like request is completed by php-fpm in time and successfully?

**Comment by hollodotme** [comment]
@Vanav OK, thanks, but this script is not resetting the OPCache as far as I can see. It just looks if OPCache is installed and loaded.

**Comment by hollodotme** [comment]
And as mentioned above. I would also need the calling code where you create and send the request to php-fpm and fetch the response and the used version of the fast-cgi-client library as well. Thanks.

**Comment by Vanav** [comment]
But I don't see other scripts. Maybe @gordalina can consult about script, code that halts and versions.

**Comment by gordalina** [comment]
@hollodotme this is the steps that are executed when a user does a sample request as clearing opcache:

1. user runs: ```cachetool opcache:reset --fcgi=/var/run/php5-fpm.sock```
1. cachetool creates a temporary file with the contents as above
1. cachetool asks fcgi to execute that script (see here: https://github.com/gordalina/cachetool/blob/master/src/Adapter/FastCGI.php#L130)
1. When the program hangs, it does so at that line, a response is never returned.

@hollodotme the fast-cgi-client version should be at least 3.0.0, @Vanav can you provide the cachetool version you are using?

**Comment by hollodotme** [comment]
@gordalina OK thanks, I'll check it out with cachetool v4.1.1 which @Vanav said they use. I'll get back here as soon as I know what's going on.

**Comment by gordalina** [comment]
@hollodotme for version 4.1.1 cachetool was not using your library but https://github.com/adoy/PHP-FastCGI-Client
I'll re-open the ticket if I have more reports with the same issue (that use your library).
@Vanav can you upgrade to the latest version of cachetool to check if it still happens?
